### PR TITLE
Update build-publish-linux.yml to use autdiwheel

### PR DESCRIPTION
**Pull request by MatPoliquin**
Attempt to use auditwheel to make the wheel compliant with manylinux

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Could we fix the link checker or remove it

**Comment by MatPoliquin** [comment]
> Could we fix the link checker or remove it

I would be in favor of removing it for now as it's not very reliable, sometimes it works sometimes it doesn't.
Maybe it's a problem with our integration but there is more urgent priorities for now.
I would add the task to Monday.com board but still don't have permissions

**Comment by zbeucler2018** [comment]
Whats the status on this? I'd like to help if needed

**Comment by zbeucler2018** [comment]
> @zbeucler2018 could you make a Pr to remove the link checker? 

Already done on MR#63 !

**Pull request closed without merging**
