### PR TITLE
Py311 + Py312 support

### PR DESCRIPTION
**Pull request by thatguy11325**
Haven't tested this PR beyond running `make`, `make test` and `pip3 install .`, but this PR
- Fixes a small platform detection issue in CMakeLists.txt
- Bumps the pybind11 branch cloned with `git subrepo` to the newest version (v2.11.1) to enable Python 3.11 and 3.12 support
- Raises the version pin in setup.py

### CODE REVIEW

**Comment by MatPoliquin** [comment]
thank you for this! I will test it a bit more first before merging it

**Comment by MatPoliquin** [comment]
3.12 package fails:
[https://github.com/Farama-Foundation/stable-retro/actions/runs/6872667848/job/18693185399?pr=79](https://github.com/Farama-Foundation/stable-retro/actions/runs/6872667848/job/18693185399?pr=79)

**Comment by thatguy11325** [comment]
I believe I fixed the errors :)

**Comment by thatguy11325** [comment]
Thanks for rerunning the tests. Looks like there's some issues with pre-commit formatting the files weirdly.

**Comment by MatPoliquin** [comment]
Seems the .github folder of pybind11 was committed as well, is there a need for that?

**Comment by thatguy11325** [comment]
There isn't. I'll remove it. It's an artifact of using `git subrepo clone` (what was used to add pybind11 to the repo per the commit history) to pull the newer version of pybind11.

**Review by MatPoliquin — APPROVED** [review]

**Pull request merged**
