### PR TITLE
windows 3.10 build capability

### PR DESCRIPTION
**Pull request by onaclov2000**
Calling build_windows.bat on a system that has docker installed should build you a whl file, at which point you can pull it out of the container, and pip install it, and it works on windows.

### CODE REVIEW

**Comment by onaclov2000** [comment]
I'm not sure why the pre-commit is failing, I thought the flake8 or whatever stuff automatically fixes certain issues and doesn't fail on that, based on the output it looks like it's complaining about trailing whitespace?

**Comment by onaclov2000** [comment]
Finally ran flake8 stuff locally so pre-commit passes.

**Comment by pseudo-rnd-thoughts** [comment]
@onaclov2000 Would you be able to add a version of this that runs in CI with github actions? 
I think that we can run it with a single version. This will just allow us to know that the windows build still works and none of our other code breaks

**Comment by onaclov2000** [comment]
@pseudo-rnd-thoughts I don't know a whole lot about github actions yet, I'm not sure how to either call docker, and run docker, or call all the commands referenced in docker individually if that makes sense. I might give it a shot later, but I'm not sure how fast I'll be able to do that.

**Comment by pseudo-rnd-thoughts** [comment]
For reference, this is how we do docker based CI testing in gymnasium - https://github.com/Farama-Foundation/Gymnasium/blob/main/.github/workflows/build.yml

**Comment by onaclov2000** [comment]
Ahh not sure how I missed that, interesting. Does it actually build the package for each of the tested targets?

**Pull request merged**
